// Declare modules
pub mod modules;

// Import commands from modules
use modules::commands;
use modules::content_library;
use modules::files;
use modules::h0xc_control_message;
use modules::ipfs_cache;
use modules::ipfs_publish;
use modules::journal;
use modules::process;
use modules::provider_settings;
use modules::rpc;
use modules::runtime;
use modules::short_message;
use modules::short_message_suggestions;
use modules::short_message_table_packs;
use modules::stratum;
use modules::vault;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            // Commands from modules::commands
            commands::list_utxos,
            commands::broadcast_advanced_transaction,
            commands::dashboard_data,
            commands::get_receive_addresses,
            commands::new_address,
            commands::get_change_address,
            commands::get_network_mode,
            commands::send_hemp,
            commands::preview_send_hemp,
            commands::preview_transfer_asset,
            commands::get_transaction_history,
            commands::list_assets,
            commands::list_qualifier_assets,
            commands::transfer_asset,
            commands::issue_asset,
            commands::ban_old_peers,
            commands::get_banned_peers,
            commands::unban_peer,
            commands::dump_priv_key,
            commands::import_priv_key,
            commands::export_wallet_migration,
            commands::validate_wallet_migration,
            commands::restore_wallet_migration,
            commands::wallet_encrypt,
            commands::wallet_encrypt_named,
            commands::wallet_unlock,
            commands::wallet_unlock_named,
            commands::wallet_lock,
            commands::wallet_lock_named,
            commands::change_wallet_password,
            commands::change_wallet_password_named,
            commands::get_net_info,
            commands::execute_ping,
            commands::check_open_port,
            commands::run_shell_command,
            commands::shell_autocomplete,
            commands::get_advanced_shell_enabled,
            commands::set_advanced_shell_enabled,
            commands::run_cli_command,
            commands::run_cli_args,
            commands::get_info,
            commands::list_address_groupings,
            commands::get_asset_data,
            commands::list_network_assets,
            commands::list_asset_holders,
            commands::check_ownership_token,
            commands::reissue_asset,
            commands::lock_asset_supply,
            commands::update_asset_metadata,
            commands::issue_unique_asset,
            commands::preview_issue_asset,
            commands::preview_issue_sub_asset,
            commands::preview_issue_unique_asset,
            commands::preview_reissue_asset,
            commands::preview_issue_qualifier_asset,
            commands::issue_qualifier_asset,
            commands::preview_issue_restricted_asset,
            commands::issue_restricted_asset,
            commands::preview_add_tag_to_address,
            commands::add_tag_to_address,
            commands::preview_remove_tag_from_address,
            commands::remove_tag_from_address,
            commands::check_address_tag,
            commands::list_tags_for_address,
            commands::list_addresses_for_tag,
            commands::get_verifier_string,
            commands::list_global_restrictions,
            commands::check_global_restriction,
            commands::request_snapshot,
            commands::get_snapshot_request,
            commands::list_snapshot_requests,
            commands::cancel_snapshot_request,
            commands::get_asset_snapshot,
            commands::preview_distribute_reward,
            commands::distribute_reward,
            commands::get_distribute_reward_status,
            // Raw Transaction Commands
            commands::decode_raw_transaction,
            commands::test_mempool_accept,
            commands::create_unsigned_raw_transaction,
            // Messaging Commands
            commands::get_messaging_info,
            commands::view_asset_messages,
            commands::view_channel_messages,
            commands::view_message_channels,
            commands::subscribe_to_channel,
            commands::unsubscribe_from_channel,
            commands::preview_send_announcement,
            commands::estimate_announcement_fee,
            commands::send_announcement,
            // H0XC Channel Authority Commands
            commands::h0xc_resolve_authority_addresses,
            commands::h0xc_filter_tagged_channels,
            // H0XC Control Frame Commands
            h0xc_control_message::h0xc_control_encode_delete,
            h0xc_control_message::h0xc_control_encode_leave,
            h0xc_control_message::h0xc_control_encode_status,
            h0xc_control_message::h0xc_control_encode_report_message,
            h0xc_control_message::h0xc_control_encode_report_channel,
            h0xc_control_message::h0xc_control_decode,
            // IPFS Commands
            commands::ipfs_validate,
            commands::ipfs_gateway_url,
            // Commands from modules::process
            process::start_node,
            process::stop_node,
            process::restart_node_with_wallet,
            process::set_network_mode,
            process::restart_app,
            process::restore_wallet,
            process::restore_legacy_wallet_dat,
            process::switch_to_legacy_wallet_dat,
            process::validate_wallet_file,
            process::detect_wallet_file_type,
            process::create_new_wallet,
            // Commands from modules::files
            files::init_config,
            files::read_config,
            files::write_config,
            files::read_log,
            files::truncate_log,
            files::open_data_dir,
            files::backup_data_folder,
            files::backup_data_folder_to,
            files::create_default_config,
            files::get_binary_status,
            files::extract_binaries,
            files::load_address_book,
            files::save_address_book,
            files::extract_snapshot,
            files::read_text_file,
            files::write_text_file,
            files::dialog_read_text_file,
            files::dialog_write_text_file,
            files::check_config_exists,
            files::get_data_folder_info,
            files::load_app_settings,
            files::save_app_settings,
            files::get_commander_settings_path,
            files::set_core_data_dir,
            files::reset_core_data_dir,
            files::prepare_core_data_dir_move,
            files::copy_core_data_dir_to,
            files::set_daemon_repair_mode,
            files::clear_daemon_repair_mode,
            files::get_daemon_repair_mode,
            files::set_core_binary_dir,
            files::reset_core_binary_dir,
            files::get_core_binary_dir,
            files::get_daemon_repair_status,
            runtime::get_runtime_status,
            runtime::probe_default_daemon,
            runtime::take_daemon_ownership,
            runtime::get_daemon_ownership,
            runtime::release_daemon_ownership,
            runtime::identify_running_daemon,
            runtime::wait_for_daemon_ready,
            runtime::get_daemon_process_identity,
            rpc::get_rpc_auth_status,
            rpc::rpc_get_blockchain_info,
            rpc::rpc_get_network_info,
            rpc::rpc_get_wallet_info,
            rpc::rpc_call,
            rpc::rpc_dashboard,
            journal::get_tx_journal_path,
            journal::list_tx_journal_entries,
            journal::add_tx_journal_entry,
            journal::update_tx_journal_entry,
            journal::delete_tx_journal_entry,
            journal::export_tx_journal,
            // Consolidation Commands
            commands::preview_wallet_consolidation,
            commands::broadcast_wallet_consolidation,
            commands::plan_wallet_consolidation,
            commands::get_policy_diagnostics,
            // Additional Commands
            commands::backup_wallet,
            commands::backup_wallet_to,
            // Content Library Commands
            content_library::content_library_list,
            content_library::content_library_get,
            content_library::content_library_create,
            content_library::content_library_update,
            content_library::content_library_delete,
            content_library::content_library_get_file,
            content_library::content_library_import_cid,
            content_library::content_library_link_cid,
            content_library::content_library_set_folder,
            content_library::content_library_open_root_folder,
            content_library::content_library_open_package_folder,
            content_library::content_library_create_folder,
            content_library::content_library_delete_folder,
            content_library::content_library_list_folders,
            content_library::content_library_duplicate,
            content_library::content_library_move_packages,
            // IPFS Cache / Gateway Commands
            ipfs_cache::content_library_fetch_cid,
            ipfs_cache::content_library_fetch_cid_path,
            ipfs_cache::content_library_get_cached,
            ipfs_cache::content_library_refresh_cached,
            ipfs_cache::content_library_has_cache,
            ipfs_cache::content_library_cache_status,
            ipfs_cache::content_library_clear_cache,
            ipfs_cache::content_library_get_cache_dir,
            ipfs_cache::content_library_default_gateways,
            // IPFS Publish Commands
            ipfs_publish::ipfs_test_publish_provider,
            ipfs_publish::content_library_publish_package,
            ipfs_publish::content_library_prepare_publish_package,
            ipfs_publish::ipfs_list_provider_pins,
            ipfs_publish::ipfs_unpin_provider_cid,
            ipfs_publish::ipfs_unpin_provider_cids,
            ipfs_cache::content_library_save_cached,
            ipfs_cache::content_library_open_cached_file,
            ipfs_cache::content_library_open_cache_folder,
            ipfs_cache::content_library_write_to_path,
            ipfs_cache::dialog_content_library_save_cached,
            ipfs_cache::dialog_content_library_write_to_path,
            // Provider Settings Commands
            provider_settings::ipfs_get_provider_settings,
            provider_settings::ipfs_update_provider_settings,
            provider_settings::ipfs_unlock_vault,
            provider_settings::ipfs_lock_vault,
            provider_settings::ipfs_vault_status,
            provider_settings::ipfs_migrate_provider_tokens_to_vault,
            provider_settings::ipfs_vault_provider_status,
            provider_settings::ipfs_provider_token_presence,
            provider_settings::ipfs_vault_remove_provider_token,
            provider_settings::ipfs_vault_import_bundle_replace,
            // Stratum Commands
            stratum::start_stratum_server,
            stratum::stop_stratum_server,
            stratum::get_stratum_status,
            stratum::validate_stratum_address,
            stratum::get_stratum_bind_candidates,
            stratum::reset_stratum_stats,
            // Short Message Commands
            short_message::short_message_encode,
            short_message::short_message_encode_built_in,
            short_message::short_message_encode_chat,
            short_message::short_message_encode_chat_built_in,
            short_message::short_message_decode,
            short_message::short_message_decode_built_in,
            short_message_suggestions::short_message_suggestions,
            short_message_suggestions::short_message_suggestions_built_in,
            short_message_suggestions::short_message_emojis,
            short_message_suggestions::short_message_emojis_built_in,
            short_message_suggestions::short_message_prepare_active_table_pack,
            short_message_suggestions::short_message_prepare_built_in_table_pack,
            short_message_table_packs::short_message_list_table_packs,
            short_message_table_packs::short_message_get_active_table_pack,
            short_message_table_packs::short_message_import_table_pack,
            short_message_table_packs::short_message_export_built_in_table_pack,
            short_message_table_packs::short_message_select_table_pack,
            short_message_table_packs::short_message_delete_table_pack,
            short_message_table_packs::short_message_reset_table_pack,
            // Vault Commands
            vault::vault_get_info,
            vault::vault_get_vault_overview,
            vault::vault_get_vault_index,
            vault::vault_set_vault_label,
            vault::vault_set_active_export_path,
            vault::vault_autosave_active_export_path,
            vault::vault_archive_current_vault,
            vault::vault_read_raw_content,
            vault::vault_setup,
            vault::vault_get_supported_record_types,
            vault::vault_get_supported_derivation_profiles,
            vault::vault_get_vault_path,
            vault::vault_export_bundle_to_path,
            vault::vault_validate_import_bundle,
            vault::vault_import_wallet_migration_record_from_path,
            vault::vault_export_current_wallet_migration_record,
            vault::vault_restore_wallet_migration_record,
            vault::vault_list_wallet_migration_records,
            vault::vault_remove_wallet_migration_record,
            // Vault WebCom / Hemp0x Vault Interop Commands
            vault::vault_get_webcom_interop_summary,
            vault::vault_get_address_book_record_summary,
            vault::vault_export_address_book_record,
            vault::vault_import_address_book_record,
            // Vault Wallet Alignment (slice 64c)
            vault::vault_get_wallet_alignment_status,
            vault::vault_create_or_update_alignment_record,
            // Vault WebCom -> Core Bridge (slice 64d)
            vault::vault_connect_webcom_primary_wallet_to_core,
            vault::vault_get_wallet_alignment_status_v2,
            vault::vault_create_or_update_connection_intent,
            // Vault cached-session wrappers for the Wallet page
            provider_settings::ipfs_vault_setup_and_unlock,
            provider_settings::ipfs_vault_unlock_status,
            provider_settings::ipfs_vault_list_wallet_migration_records,
            provider_settings::ipfs_vault_export_current_wallet_migration_record,
            provider_settings::ipfs_vault_restore_wallet_migration_record,
            provider_settings::ipfs_vault_remove_wallet_migration_record,
            provider_settings::ipfs_vault_import_wallet_migration_record_from_path,
            // Vault WebCom / Hemp0x Vault Interop Cached-Session Wrappers
            provider_settings::ipfs_vault_get_webcom_interop_summary,
            provider_settings::ipfs_vault_get_address_book_record_summary,
            provider_settings::ipfs_vault_export_address_book_record,
            provider_settings::ipfs_vault_import_address_book_record,
            // Vault Wallet Alignment cached-session wrappers (slice 64c)
            provider_settings::ipfs_vault_get_wallet_alignment_status,
            provider_settings::ipfs_vault_create_or_update_alignment_record,
            // Vault WebCom -> Core Bridge cached-session wrappers (slice 64d)
            provider_settings::ipfs_vault_connect_webcom_primary_wallet_to_core,
            // Vault WebCom -> Core guided connect wrapper (slice 64f)
            provider_settings::ipfs_vault_connect_webcom_primary_wallet_to_core_guided,
            provider_settings::ipfs_vault_get_wallet_alignment_status_v2,
            provider_settings::ipfs_vault_preview_connect_webcom_primary_to_core,
            provider_settings::ipfs_vault_preview_export_core_wallet_to_webcom_primary,
            provider_settings::ipfs_vault_backup_current_core_wallet_before_alignment,
            // Vault Commander-managed wallet commands (slice 64i)
            vault::vault_set_active_wallet_name,
            vault::vault_get_active_wallet_name,
            vault::vault_get_active_wallet_startup_state,
            vault::vault_restart_core_with_wallet,
            vault::vault_load_wallet_into_core,
            vault::vault_check_named_wallet_restore_state,
            vault::vault_unload_wallet,
            vault::vault_refresh_wallet_utxos,
            vault::vault_recover_wallet_history,
            vault::vault_start_wallet_history_recovery,
            vault::vault_restore_from_recovery_phrase,
            vault::vault_generate_bip39_mnemonic,
            // Vault Core-to-WebCom promotion (slice 66/66b)
            vault::ipfs_vault_promote_core_migration_to_portable_primary,
            vault::ipfs_vault_promote_core_wallet_to_portable_primary,
            // Vault advanced export (slice 66b)
            vault::vault_export_core_migration_wallet,
            // Vault passphrase rotation + unload/fallback (slice 64p)
            vault::vault_change_passphrase,
            vault::vault_unload_vault_and_use_wallet_dat,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
